<?php
/**
 * Sorted Chunky font glyphs by pixel density (low to high)
 * This is a placeholder file with basic characters if the density analyzer cannot run
 * Normally this file would be generated by tools/generateChunkyGlyphDensity.php
 */

return [
    ' ', '.', '`', '\'', ':', ';', '"', '!', 'i', 'I', 'l', '|', '-', '_', '·', 
    'j', '(', ')', '[', ']', '{', '}', '<', '>', '/', '\\', '∞', '≈', '≠', '≤', '≥',
    '+', '=', '×', '÷', '±', '*', '#', '@', '&', '%', 'o', 'O', '◘', '○', '◙', 
    '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'a', 'b', 'c', 'd', 'e',
    'f', 'g', 'h', 'k', 'm', 'n', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x',
    'y', 'z', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'J', 'K', 'L', 'M', 'N',
    'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '◄', '►', '▲', '▼',
    '↑', '↓', '←', '→', '↔', '↕', '∟', '⌂', '☺', '☻', '♥', '♦', '♣', '♠', '•',
    '│', '─', '┌', '┐', '└', '┘', '├', '┤', '┬', '┴', '┼', '═', '║', '╔', '╗', '╚', '╝', 
    '╠', '╣', '╦', '╩', '╬', '░', '▒', '▓', '■', '█'
]; 